CREATE TABLE IF NOT EXISTS `user_bazi_profile` (
  `id` bigint NOT NULL COMMENT 'id',
  `userId` bigint NOT NULL COMMENT '用户 id',
  `gender` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT 'unknown' COMMENT '性别',
  `birthDate` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '出生日期',
  `birthTime` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '出生时间',
  `birthPlace` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '出生地',
  `useTrueSolarTime` tinyint NOT NULL DEFAULT '0' COMMENT '是否使用真太阳时',
  `calendarType` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'solar' COMMENT '历法类型',
  `yearPillar` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '年柱',
  `monthPillar` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '月柱',
  `dayPillar` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '日柱',
  `hourPillar` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '时柱',
  `dayMaster` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '日主',
  `dayMasterElement` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '日主五行',
  `baziJson` longtext COLLATE utf8mb4_unicode_ci COMMENT '结构化八字排盘',
  `todayJson` longtext COLLATE utf8mb4_unicode_ci COMMENT '今日流日冲克',
  `aiJson` longtext COLLATE utf8mb4_unicode_ci COMMENT 'DeepSeek 结构化原始结果',
  `aiAnalysis` longtext COLLATE utf8mb4_unicode_ci COMMENT 'DeepSeek 八字解析',
  `constitutionSummary` longtext COLLATE utf8mb4_unicode_ci COMMENT 'DeepSeek 体质总结',
  `healthAdvice` longtext COLLATE utf8mb4_unicode_ci COMMENT 'DeepSeek 养生建议',
  `wood` tinyint unsigned NOT NULL DEFAULT '20' COMMENT '木',
  `fire` tinyint unsigned NOT NULL DEFAULT '20' COMMENT '火',
  `earth` tinyint unsigned NOT NULL DEFAULT '20' COMMENT '土',
  `metal` tinyint unsigned NOT NULL DEFAULT '20' COMMENT '金',
  `water` tinyint unsigned NOT NULL DEFAULT '20' COMMENT '水',
  `analyzedAt` datetime DEFAULT NULL COMMENT '最近分析时间',
  `createTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `isDelete` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_userId` (`userId`),
  KEY `idx_updateTime` (`updateTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户八字体质分析档案';
