CREATE TABLE IF NOT EXISTS `user_bazi_relation` (
  `id` bigint NOT NULL COMMENT 'id',
  `userId` bigint NOT NULL COMMENT '用户 id',
  `baziProfileId` bigint NOT NULL COMMENT '八字档案 id',
  `currentCity` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '当前城市',
  `relationshipStatus` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT 'unknown' COMMENT '关系状态',
  `careerStage` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT 'unknown' COMMENT '事业阶段',
  `focusQuestion` varchar(1200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关注问题',
  `relationJson` longtext COLLATE utf8mb4_unicode_ci COMMENT '结构化关系画像',
  `aiSummary` longtext COLLATE utf8mb4_unicode_ci COMMENT '总体关系总结',
  `relationshipAdvice` longtext COLLATE utf8mb4_unicode_ci COMMENT '人际关系建议',
  `marriageAdvice` longtext COLLATE utf8mb4_unicode_ci COMMENT '婚姻爱情建议',
  `careerAdvice` longtext COLLATE utf8mb4_unicode_ci COMMENT '事业发展建议',
  `wealthAdvice` longtext COLLATE utf8mb4_unicode_ci COMMENT '财运建议',
  `luckyCities` longtext COLLATE utf8mb4_unicode_ci COMMENT '旺运城市 JSON',
  `luckyDirections` longtext COLLATE utf8mb4_unicode_ci COMMENT '旺运方位 JSON',
  `fortunateElements` longtext COLLATE utf8mb4_unicode_ci COMMENT '助运五行 JSON',
  `scoreJson` longtext COLLATE utf8mb4_unicode_ci COMMENT '关系分数 JSON',
  `analyzedAt` datetime DEFAULT NULL COMMENT '最近分析时间',
  `createTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `isDelete` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_userId` (`userId`),
  KEY `idx_baziProfileId` (`baziProfileId`),
  KEY `idx_updateTime` (`updateTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户八字人际关系与运势画像';
