CREATE TABLE IF NOT EXISTS `user_divination_record` (
  `id` bigint NOT NULL COMMENT 'id',
  `userId` bigint NOT NULL COMMENT '用户 id',
  `question` varchar(800) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '具体问事',
  `dateText` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '起卦日期',
  `signNo` int DEFAULT NULL COMMENT '签号',
  `signTitle` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '签题',
  `signLevel` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '签位',
  `hexagramName` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '本卦',
  `changedHexagramName` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '变卦',
  `lowerTrigram` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '下卦',
  `upperTrigram` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '上卦',
  `changedLowerTrigram` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '变卦下卦',
  `changedUpperTrigram` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '变卦上卦',
  `linesJson` longtext COLLATE utf8mb4_unicode_ci COMMENT '六爻值 JSON',
  `movingLinesJson` longtext COLLATE utf8mb4_unicode_ci COMMENT '动爻 JSON',
  `extraInfo` varchar(800) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '补充背景',
  `requestJson` longtext COLLATE utf8mb4_unicode_ci COMMENT '前端起卦请求 JSON',
  `aiJson` longtext COLLATE utf8mb4_unicode_ci COMMENT 'DeepSeek 原始结构化结果 JSON',
  `signText` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '签文',
  `overall` longtext COLLATE utf8mb4_unicode_ci COMMENT '总体分析',
  `healthAnalysis` longtext COLLATE utf8mb4_unicode_ci COMMENT '健康分析',
  `relationshipAnalysis` longtext COLLATE utf8mb4_unicode_ci COMMENT '姻缘关系分析',
  `careerAnalysis` longtext COLLATE utf8mb4_unicode_ci COMMENT '事业分析',
  `wealthAnalysis` longtext COLLATE utf8mb4_unicode_ci COMMENT '财富分析',
  `luckAnalysis` longtext COLLATE utf8mb4_unicode_ci COMMENT '运气分析',
  `liuyaoAnalysis` longtext COLLATE utf8mb4_unicode_ci COMMENT '六爻问事分析',
  `comprehensiveAnalysis` longtext COLLATE utf8mb4_unicode_ci COMMENT '综合分析',
  `actionPlanJson` longtext COLLATE utf8mb4_unicode_ci COMMENT '行动建议 JSON',
  `riskNotice` longtext COLLATE utf8mb4_unicode_ci COMMENT '风险提示',
  `analyzedAt` datetime DEFAULT NULL COMMENT '分析时间',
  `createTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `isDelete` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_userId_updateTime` (`userId`,`updateTime`),
  KEY `idx_hexagramName` (`hexagramName`),
  KEY `idx_signNo` (`signNo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户求签问卜记录';
